const actionTypes = {
    TOGGLE_TASK_IS_COMPLETED: 'TOGGLE_TASK_IS_COMPLETED',
    ADD_NEW_TASK: 'ADD_NEW_TASK',
    LOAD_TASKS_FROM_LOCAL_STORAGE: 'LOAD_TASKS_FROM_LOCAL_STORAGE',
    DELETE_TASK: 'DELETE_TASK',

};

export default actionTypes;